name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers
          restore-keys: ${{ runner.os }}-playwright-browsers
      - name: Install Playwright browsers
        run: npx playwright install && sudo npx playwright install-deps
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test:unit
      - name: Run projects
        run: npm start &
        continue-on-error: true
      - name: e2e tests
        run: npm run test:e2e
      - name: logs
        run: echo "${{ secrets.RENDER_SERVICE_ID }}" && echo "${{ secrets.RENDER_API_KEY }}"
      - name: Trigger deployment
        run: curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"
